package VentanasAutenticacion;

import Principal.main;
import VentanasUsuario.InicioUsuario;
import javax.swing.table.DefaultTableModel;

public class Archivos extends javax.swing.JFrame {

    /**
     * Creates new form Archivos
     */
    public Archivos() {
        initComponents();
        
        // Centra la ventana en pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnMostrarBbitacora = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        btnMostrarBbitacora.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnMostrarBbitacora.setText("Ver Bitacora");
        btnMostrarBbitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarBbitacoraActionPerformed(evt);
            }
        });

        btnInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInicio.setText("Regresar al inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnMostrarBbitacora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInicio)))
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarBbitacora)
                    .addComponent(btnInicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarBbitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarBbitacoraActionPerformed
        
        DefaultTableModel modelo = new DefaultTableModel();
    
        // Definir columnas
        modelo.addColumn("Operacion");
        modelo.addColumn("Usuario");
        modelo.addColumn("Status");
                
        // Actualizamos la bitacora
        main.bitacora.LeerArchivo();
        
        // leyendo las lineas del archivo => Operacion:opcion;Usuario:nombre;Status:opcion
        for(String linea: main.bitacora.getContenido()) {
            // Separamos por punto y coma (;)
            String[] partes = linea.split(";");
            
            // Verificamos que tenga 3 elementos => Operacion, Usuario, Status
            if (partes.length == 3) {
                String operacion = "";
                String usuario = "";
                String status = "";

                // Recorremos nuestras lineas del archivo bitacora
                for (String parte : partes) {
                    // Separamos por ':'
                    String[] data = parte.split(":");
                    
                    // Verificamos que tenga 2 posiciones
                    // Operacion:Login quedaria como => data[0] = "Operacion" y data[1] = "Login"
                    if (data.length == 2) {
                        switch (data[0]) {
                            case "Operacion":
                                operacion = data[1];
                                break;
                            case "Usuario":
                                usuario = data[1];
                                break;
                            case "Status":
                                status = data[1];
                                break;
                        }
                    }
                }

                // Agregamos solo los valores
                modelo.addRow(new Object[]{operacion, usuario, status});
            }          
        }

        // Asignar modelo a la tabla
        tabla.setModel(modelo);
    }//GEN-LAST:event_btnMostrarBbitacoraActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // Cerrando ventana y liberando recursos
        this.dispose();
        
        // Creando ventana de InicioUsuario
        InicioUsuario iu = new InicioUsuario();
        
        // mostrando ventana
        iu.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnMostrarBbitacora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
