package VentanasAutenticacion;

import Entidades.Usuario;
import Principal.main;
import VentanasAdmin.PanelAdmin;
import VentanasUsuario.InicioUsuario;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // Centra la ventana en pantalla
        this.setLocationRelativeTo(null);
        
        // Estableciendo el boton ingresar como principal para que funcione al dat Enter y no solo cuando se le da click
        getRootPane().setDefaultButton(btnIngresar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblRegistrar = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("User");

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password");

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(0, 0, 255));
        lblRegistrar.setText("No tiene una cuenta? Registrese aqui!");
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Registrarse(evt);
            }
        });

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPassword)
                            .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 119, Short.MAX_VALUE)
                        .addComponent(lblRegistrar)
                        .addGap(68, 68, 68))))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegistrar)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Metodo utilizado para mostrar la ventana de Registro
    private void Registrarse(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Registrarse
                
        // Cierra la ventana y libera los recursos
        this.dispose();
        
        // Creacion de la ventana de registro
        Register ventanaRegistro = new Register();
        
        // Mostrando la ventana de registro
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_Registrarse

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String username = txtUser.getText();
        
        if(username.equals("admin")) {
            char[]entrada = this.txtPassword.getPassword();
            String password = new String(entrada);
            if (password.equals("admin")) {
                // Cerrando ventana actual y liberando recursos
                this.dispose();
                
                // Creando la ventana del panel de administrador
                PanelAdmin panelAdministrador = new PanelAdmin();
                
                // Mostrando la ventana del panel de administrador
                panelAdministrador.setVisible(true);
                
                // Salir de la funcion para no ejecutar lo que esta debajo
                return;
            }
            
        }
        
        Usuario user = main.ObtenerUsuario(username);
        
        // Si es diferente de null significa que encontro al usuario
        if (user != null) {
            char[] entrada = this.txtPassword.getPassword();
            String contrasenaIngresada = new String(entrada);
            
            // Verificamos que la contrasena ingresada coincida con la contrasena del usuario actual
            if (user.ContrasenaCorrecta(contrasenaIngresada)) {
                // Registrando accion en la bitacora
                main.bitacora.AgregarLinea("Operacion:Login;Usuario:" + username + ";Status:Correcto");

                // Mostrando mensaje de Login exitoso
                JOptionPane.showMessageDialog(this, "Bienvenido " + username);                
                
                // TODO: Segun el rol redirigir
                
                // Creando ventana de inicio para el usuario logueado
                InicioUsuario ventanaInicioUsuario = new InicioUsuario();
                
                // Mostrando la ventana
                ventanaInicioUsuario.setVisible(true);

                // Cerrando ventana de login y liberando recursos
                this.dispose();
            }
        } else {
            // Registrando accion en la bitacora => pueden manejarlo de forma diferente
            main.bitacora.AgregarLinea("Operacion:Login;Usuario:" + username + ";Status:Erroneo");
            
            // Mostrando mensaje de login incorrecto
            JOptionPane.showMessageDialog(this, "Credenciales incorrectas!");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
