package VentanasAdmin;

import Entidades.Usuario;
import Principal.Inicio;
import javax.swing.JOptionPane;

/**
 * ========================================================================
 * Clase: AgregarOperador
 * ========================================================================
 * Esta ventana permite agregar un nuevo operador al sistema.
 * 
 * FUNCIONAMIENTO:
 * 1. El usuario ingresa: código, nombre, carrera y contraseña
 * 2. Se valida que todos los campos estén llenos
 * 3. Se valida que el código no exista en el sistema
 * 4. Se crea un nuevo objeto Usuario con rol = 2 (Operador)
 * 5. Se agrega al arreglo global Inicio.usuarios
 * 6. Se guarda en el archivo cuentas.txt
 * 
 * COMUNICACIÓN CON LA VENTANA PADRE:
 * - Esta ventana recibe una referencia a GestionesAdmin (ventanaPadre)
 * - Cuando se confirma la creación, llama a guardarYRecargarOperadores()
 * - Esto actualiza la tabla en la ventana padre
 * ========================================================================
 */
public class AgregarOperador extends javax.swing.JFrame {
    
    // ========================================================================
    // VARIABLES DE INSTANCIA
    // ========================================================================
    
    // Referencia a la ventana padre (GestionesAdmin)
    // Se usa para actualizar la tabla cuando se agrega un operador
    private GestionesAdmin ventanaPadre;
    
    // ========================================================================
    // CONSTRUCTOR
    // ========================================================================
    /**
     * Constructor de la ventana de agregar operador.
     * 
     * @param padre - Referencia a la ventana GestionesAdmin (para actualizar la tabla)
     */
    public AgregarOperador(GestionesAdmin padre) {
        // PASO 1: Inicializar componentes gráficos (generado por NetBeans)
        initComponents();
        
        // PASO 2: Centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);
        
        // PASO 3: Guardar la referencia a la ventana padre
        this.ventanaPadre = padre;
        
        // PASO 4: Configurar los eventos de los botones
        configurarEventos();
        
        // NOTA: Los campos inician vacíos porque es un nuevo operador
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCarrera = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        lblContrasena = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConfirmar.setText("Confirmar");

        btnCancelar.setText("Cancelar");

        lblNombre.setText("Nombre");

        lblCarrera.setText("Carrera");

        lblCodigo.setText("Codigo");

        lblContrasena.setText("Contraseña");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCarrera, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCarrera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCodigo)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCarrera)
                .addGap(18, 18, 18)
                .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblContrasena)
                .addGap(18, 18, 18)
                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ========================================================================
    // EVENTOS DE BOTONES (Código que se ejecuta al hacer clic)
    // ========================================================================
    
    /**
     * EVENTO: Click en botón "Confirmar"
     * -----------------------------------------------------------------------
     * Se ejecuta cuando el usuario hace clic en el botón "Confirmar".
     * 
     * FLUJO:
     * 1. Validar que los campos no estén vacíos
     * 2. Validar que el código no exista
     * 3. Mostrar diálogo de confirmación
     * 4. Crear el nuevo operador
     * 5. Agregarlo al arreglo global
     * 6. Guardar en el archivo
     * 7. Cerrar esta ventana
     */
    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // PASO 1: Validar que todos los campos estén llenos
        String[] datos = validarCamposLlenos();
        if (datos == null) {
            return; // Si la validación falla, salir del método
        }
        
        // Extraer los datos validados del arreglo
        String codigo = datos[0];
        String nombre = datos[1];
        String carrera = datos[2];
        String contrasena = datos[3];
        
        // PASO 2: Validar que el código no exista
        if (!validarCodigoNoExiste(codigo)) {
            return; // Si el código ya existe, salir del método
        }
        
        // PASO 3: Mostrar diálogo de confirmación
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de agregar el nuevo operador?\n\n" +
            "Código: " + codigo + "\n" +
            "Nombre: " + nombre + "\n" +
            "Carrera: " + carrera,
            "Confirmar creación", 
            JOptionPane.YES_NO_OPTION);
        
        // PASO 4: Verificar si el usuario confirmó
        if (confirmacion != JOptionPane.YES_OPTION) {
            return; // Si no confirmó, salir del método
        }
        
        // PASO 5: Crear el nuevo operador
        // El primer parámetro (2) es el rol de Operador
        Usuario nuevoOperador = new Usuario(2, codigo, contrasena, nombre, carrera);
        
        // PASO 6: Verificar que hay espacio en el arreglo global
        if (Inicio.totalUsuarios < Inicio.usuarios.length) {
            // Agregar el nuevo operador al arreglo global
            Inicio.usuarios[Inicio.totalUsuarios] = nuevoOperador;
            Inicio.totalUsuarios++; // Incrementar el contador
            
            // PASO 7: Guardar los cambios en el archivo
            guardarCambios();
            
            // PASO 8: Mostrar mensaje de éxito
            JOptionPane.showMessageDialog(this, 
                "Operador agregado exitosamente", "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // PASO 9: Cerrar esta ventana
            this.dispose();
        } else {
            // Si no hay espacio, mostrar error
            JOptionPane.showMessageDialog(this, 
                "No hay espacio para más usuarios", "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * EVENTO: Click en botón "Cancelar"
     * -----------------------------------------------------------------------
     * Se ejecuta cuando el usuario hace clic en el botón "Cancelar".
     * 
     * Pregunta al usuario si está seguro de cancelar (para evitar pérdida
     * accidental de datos ingresados).
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Mostrar diálogo de confirmación
        int confirmacion = JOptionPane.showConfirmDialog(this, 
            "¿Está seguro de cancelar? Los cambios no se guardarán", 
            "Confirmar cancelación", 
            JOptionPane.YES_NO_OPTION);
        
        // Si el usuario confirma, cerrar la ventana
        if (confirmacion == JOptionPane.YES_OPTION) {
            this.dispose(); // Cerrar sin guardar
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

// ========================================================================
    // MÉTODOS DE INICIALIZACIÓN Y CONFIGURACIÓN
    // ========================================================================
    
    /**
     * MÉTODO: configurarEventos()
     * -----------------------------------------------------------------------
     * Configura los eventos (listeners) de los botones.
     * 
     * ¿Qué es una expresión lambda (->)?
     * Es una forma corta de escribir un ActionListener.
     * Es equivalente a crear una clase anónima que implementa ActionListener.
     */
    private void configurarEventos() {
        // Configurar el evento del botón Confirmar
        btnConfirmar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnConfirmarActionPerformed(evt);
        });
        
        // Configurar el evento del botón Cancelar
        btnCancelar.addActionListener((java.awt.event.ActionEvent evt) -> {
            btnCancelarActionPerformed(evt);
        });
    }
    
    // ========================================================================
    // MÉTODOS DE VALIDACIÓN
    // ========================================================================
    
    /**
     * MÉTODO: validarCamposLlenos()
     * -----------------------------------------------------------------------
     * Valida que todos los campos obligatorios estén llenos.
     * 
     * @return arreglo de Strings con [codigo, nombre, carrera, contrasena]
     *         o null si hay algún error
     */
    private String[] validarCamposLlenos() {
        // Obtener el texto de los campos (sin espacios al inicio/final)
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        String carrera = txtCarrera.getText().trim();
        String contrasena = new String(txtContrasena.getPassword()).trim();
        
        // Verificar que ningún campo esté vacío
        if (codigo.isEmpty() || nombre.isEmpty() || carrera.isEmpty() || contrasena.isEmpty()) {
            // Mostrar mensaje de advertencia
            JOptionPane.showMessageDialog(this, 
                "Todos los campos son obligatorios", "Validación", 
                JOptionPane.WARNING_MESSAGE);
            return null; // Retornar null indica que la validación falló
        }
        
        // Retornar los datos en un arreglo
        return new String[] {codigo, nombre, carrera, contrasena};
    }
    
    /**
     * MÉTODO: validarCodigoNoExiste()
     * -----------------------------------------------------------------------
     * Valida que el código ingresado no exista en el sistema.
     * 
     * @param codigo - Código a verificar
     * @return true si el código NO existe (es válido), false si ya existe
     * 
     * ¿Por qué es importante esta validación?
     * Cada usuario debe tener un código único. Si permitimos códigos duplicados,
     * habría problemas al buscar o modificar usuarios.
     */
    private boolean validarCodigoNoExiste(String codigo) {
        // Recorrer el arreglo global de usuarios
        for (int i = 0; i < Inicio.totalUsuarios; i++) {
            // Verificar que el usuario existe y tiene el mismo código
            if (Inicio.usuarios[i] != null && 
                Inicio.usuarios[i].getCodigo().equals(codigo)) {
                // Si encontramos el código, mostrar error
                JOptionPane.showMessageDialog(this, 
                    "El código ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                return false; // Código duplicado
            }
        }
        return true; // Código válido
    }
    
    // ========================================================================
    // MÉTODOS DE LÓGICA DE NEGOCIO
    // ========================================================================
    
    /**
     * MÉTODO: guardarCambios()
     * -----------------------------------------------------------------------
     * Guarda los cambios en el archivo y recarga la tabla en la ventana padre.
     * 
     * Este es un ejemplo de "comunicación entre ventanas".
     */
    private void guardarCambios() {
        if (ventanaPadre != null) {
            // Llamar al método de la ventana padre para guardar y recargar
            ventanaPadre.guardarYRecargarOperadores();
        }
    }
    
    // ========================================================================
    // ZONA DE CÓDIGO GENERADO POR NETBEANS
    // ========================================================================
    // ADVERTENCIA: NO modificar el código entre estos comentarios
    // NetBeans lo regenera automáticamente cuando se edita el formulario

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
