package VentanasAdmin;

import Principal.Inicio;
import VentanasAuth.Login;
import Entidades.Usuario;
import Utilidades.GenerarReportes;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 * ========================================================================
 * Clase: GestionesAdmin
 * ========================================================================
 * Esta ventana permite al administrador gestionar operadores y usuarios.
 * Tiene dos pestañas (tabs):
 *   1. Pestaña Operadores: ver, agregar, editar y buscar operadores
 *   2. Pestaña Usuarios: ver, editar, eliminar y buscar usuarios
 * 
 * CONCEPTOS IMPORTANTES:
 * - DefaultTableModel: es el modelo que guarda los datos de la tabla (filas y columnas)
 * - TableRowSorter: permite ordenar y filtrar las filas de la tabla
 * - DocumentListener: escucha cuando el usuario escribe en un campo de texto
 * ========================================================================
 */
public class GestionesAdmin extends javax.swing.JFrame {

    // ========================================================================
    // VARIABLES DE INSTANCIA (atributos de la clase)
    // ========================================================================
    
    // Modelo que guarda los datos de la tabla de operadores (filas y columnas)
    private DefaultTableModel modeloTablaOperadores;
    
    // Ordenador/filtrador para la tabla de operadores (permite buscar en tiempo real)
    private TableRowSorter<DefaultTableModel> sorterOperadores;

    // ========================================================================
    // CONSTRUCTOR - SE EJECUTA CUANDO SE CREA LA VENTANA
    // ========================================================================
    /**
     * Constructor de la ventana de gestiones del administrador.
     * Aquí se inicializa todo lo necesario para que la ventana funcione.
     */
    public GestionesAdmin() {
        // PASO 1: Inicializar los componentes gráficos (botones, tablas, etc.)
        // Este método es generado automáticamente por NetBeans
        initComponents();
        
        // PASO 2: Centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);
        
        // PASO 3: Configurar las tablas (crear columnas y hacerlas no editables)
        inicializarTablas();
        
        // PASO 4: Configurar los eventos de los botones y campos de búsqueda
        inicializarEventos();
        
        // PASO 5: Cargar los datos de operadores desde el arreglo global
        cargarOperadoresDesdeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelHeader = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        PanelBody = new javax.swing.JPanel();
        TabPanelPrincipal = new javax.swing.JTabbedPane();
        PanelOperadores = new javax.swing.JPanel();
        SeparadorOperadores = new javax.swing.JSeparator();
        btnEditarOperador = new javax.swing.JButton();
        btnAgregarOperador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaOperadores = new javax.swing.JTable();
        txtBusquedaOperador = new javax.swing.JTextField();
        PanelUsuarios = new javax.swing.JPanel();
        PanelOperadores1 = new javax.swing.JPanel();
        SeparadorUsuarios = new javax.swing.JSeparator();
        btnEditarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        txtBusquedaUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelHeader.setBackground(new java.awt.Color(153, 153, 153));

        btnCerrarSesion.setText("Cerrrar sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnInicio.setText("Regresar al panel principal");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnReportes.setText("Generar reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelBody.setBackground(new java.awt.Color(204, 204, 204));

        PanelOperadores.setBackground(new java.awt.Color(204, 204, 204));

        btnEditarOperador.setText("Editar");
        btnEditarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarOperadorActionPerformed(evt);
            }
        });

        btnAgregarOperador.setText("Agregar");
        btnAgregarOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarOperadorActionPerformed(evt);
            }
        });

        TablaOperadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaOperadores);

        javax.swing.GroupLayout PanelOperadoresLayout = new javax.swing.GroupLayout(PanelOperadores);
        PanelOperadores.setLayout(PanelOperadoresLayout);
        PanelOperadoresLayout.setHorizontalGroup(
            PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOperadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addComponent(SeparadorOperadores, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelOperadoresLayout.createSequentialGroup()
                        .addComponent(btnEditarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusquedaOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelOperadoresLayout.setVerticalGroup(
            PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelOperadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBusquedaOperador))
                .addGap(18, 18, 18)
                .addComponent(SeparadorOperadores, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        TabPanelPrincipal.addTab("Operadores", PanelOperadores);

        PanelOperadores1.setBackground(new java.awt.Color(204, 204, 204));

        btnEditarUsuario.setText("Editar");

        btnEliminarUsuario.setText("Eliminar");

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TablaUsuarios);

        javax.swing.GroupLayout PanelOperadores1Layout = new javax.swing.GroupLayout(PanelOperadores1);
        PanelOperadores1.setLayout(PanelOperadores1Layout);
        PanelOperadores1Layout.setHorizontalGroup(
            PanelOperadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelOperadores1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addComponent(SeparadorUsuarios, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelOperadores1Layout.createSequentialGroup()
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusquedaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelOperadores1Layout.setVerticalGroup(
            PanelOperadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOperadores1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOperadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelOperadores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBusquedaUsuario))
                .addGap(18, 18, 18)
                .addComponent(SeparadorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelUsuariosLayout = new javax.swing.GroupLayout(PanelUsuarios);
        PanelUsuarios.setLayout(PanelUsuariosLayout);
        PanelUsuariosLayout.setHorizontalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuariosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelOperadores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelUsuariosLayout.setVerticalGroup(
            PanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuariosLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(PanelOperadores1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        TabPanelPrincipal.addTab("Usuarios", PanelUsuarios);

        javax.swing.GroupLayout PanelBodyLayout = new javax.swing.GroupLayout(PanelBody);
        PanelBody.setLayout(PanelBodyLayout);
        PanelBodyLayout.setHorizontalGroup(
            PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanelPrincipal)
                .addContainerGap())
        );
        PanelBodyLayout.setVerticalGroup(
            PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabPanelPrincipal)
                .addContainerGap())
        );

        TabPanelPrincipal.getAccessibleContext().setAccessibleName("Operadores");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ========================================================================
    // ZONA DE INICIALIZACIÓN Y CONFIGURACIÓN
    // ========================================================================
    
    /**
     * MÉTODO: inicializarTablas()
     * -----------------------------------------------------------------------
     * Configura el modelo de la tabla de operadores.
     * 
     * ¿Qué es un DefaultTableModel?
     * Es como una matriz (tabla) que guarda los datos que se muestran en la JTable.
     * Cada fila representa un operador y cada columna un dato (código, nombre, carrera).
     * 
     * ¿Por qué sobrescribir isCellEditable?
     * Para que el usuario NO pueda editar directamente las celdas haciendo doble clic.
     * Solo se pueden modificar usando el botón "Editar".
     */
    private void inicializarTablas() {
        // Paso 1: Definir los nombres de las columnas de la tabla
        String[] columnasOperadores = {"Código", "Nombre", "Carrera"};
        
        // Paso 2: Crear el modelo con las columnas y 0 filas iniciales
        modeloTablaOperadores = new DefaultTableModel(columnasOperadores, 0) {
            
            // Sobrescribir este método para hacer que las celdas NO sean editables
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Siempre retorna false = no editable
            }
        };
        
        // Paso 3: Asignar el modelo a la tabla visual
        TablaOperadores.setModel(modeloTablaOperadores);
    }
    
    /**
     * MÉTODO: cargarOperadoresDesdeArchivo()
     * -----------------------------------------------------------------------
     * Lee el arreglo global de usuarios (Inicio.usuarios) y muestra en la tabla
     * SOLO los usuarios que tienen rol = 2 (Operadores).
     * 
     * Recordatorio de roles:
     * - Rol 1 = Administrador
     * - Rol 2 = Operador
     * - Rol 3 = Usuario normal
     */
    private void cargarOperadoresDesdeArchivo() {
        // Paso 1: Limpiar todas las filas actuales de la tabla
        modeloTablaOperadores.setRowCount(0);
        
        // Paso 2: Recorrer el arreglo global de usuarios
        for (int i = 0; i < Inicio.totalUsuarios; i++) {
            Usuario user = Inicio.usuarios[i];
            
            // Paso 3: Verificar que el usuario existe y es operador (rol = 2)
            if (user != null && user.getRol() == 2) {
                // Paso 4: Crear un arreglo con los datos a mostrar en la fila
                Object[] fila = {
                    user.getCodigo(),    // Columna 0: Código
                    user.getNombre(),    // Columna 1: Nombre
                    user.getCarrera()    // Columna 2: Carrera
                };
                // Paso 5: Agregar la fila al modelo de la tabla
                modeloTablaOperadores.addRow(fila);
            }
        }
        
        // Paso 6: Actualizar la tabla visual con el modelo actualizado
        this.TablaOperadores.setModel(modeloTablaOperadores);
    }
    
    /**
     * MÉTODO: guardarUsuariosEnArchivo()
     * -----------------------------------------------------------------------
     * Guarda todos los usuarios (excepto el admin) en el archivo cuentas.txt.
     * 
     * ¿Por qué no guardamos el admin?
     * Porque el admin está "hardcodeado" en el sistema y no cambia.
     * 
     * Formato de cada línea: rol;codigo;contrasena;nombre;carrera
     * Ejemplo: 2;202012345;pass123;Juan Pérez;Ingeniería
     */
    private void guardarUsuariosEnArchivo() {
        // Paso 1: Crear un arreglo para guardar las líneas del archivo
        String[] lineas = new String[Inicio.totalUsuarios];
        int contador = 0; // Índice para el arreglo de líneas
        
        // Paso 2: Recorrer todos los usuarios del sistema
        for (int i = 0; i < Inicio.totalUsuarios; i++) {
            Usuario user = Inicio.usuarios[i];
            
            // Paso 3: Solo guardar si NO es admin (rol != 1)
            if (user != null && user.getRol() != 1) {
                // Paso 4: Construir la línea con formato: rol;codigo;contrasena;nombre;carrera
                lineas[contador] = user.getRol() + ";" + 
                                  user.getCodigo() + ";" + 
                                  user.getContrasena() + ";" + 
                                  user.getNombre() + ";" + 
                                  user.getCarrera();
                contador++; // Incrementar el contador
            }
        }
        
        // Paso 5: Escribir todas las líneas en el archivo cuentas.txt
        Inicio.archivoCuentas.EscribirArchivo(lineas);
    }

    /**
     * MÉTODO: agregarOperador()
     * -----------------------------------------------------------------------
     * Abre una nueva ventana (AgregarOperador) para ingresar los datos de un
     * nuevo operador.
     * 
     * ¿Por qué pasamos 'this' al constructor?
     * 'this' es la referencia a ESTA ventana (GestionesAdmin).
     * La ventana hija la necesita para poder llamar a guardarYRecargarOperadores()
     * cuando se agregue el operador.
     */
    private void agregarOperador() {
        // Crear la ventana de agregar operador, pasándole esta ventana como "padre"
        AgregarOperador ventanaAgregar = new AgregarOperador(this);
        
        // Mostrar la ventana
        ventanaAgregar.setVisible(true);
    }
    
    /**
     * MÉTODO: editarOperador()
     * -----------------------------------------------------------------------
     * Permite editar un operador existente.
     * 
     * Flujo:
     * 1. Verificar que el usuario haya seleccionado una fila de la tabla
     * 2. Obtener el código del operador seleccionado
     * 3. Abrir la ventana ModificarOperador con ese código
     */
    private void editarOperador() {
        // Paso 1: Obtener el índice de la fila seleccionada
        // Retorna -1 si no hay ninguna fila seleccionada
        int filaSeleccionada = TablaOperadores.getSelectedRow();
        
        // Paso 2: Validar que haya una fila seleccionada
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un operador de la tabla", "Advertencia", 
                JOptionPane.WARNING_MESSAGE);
            return; // Salir del método
        }
        
        // Paso 3: Obtener el código del operador seleccionado (columna 0)
        String codigoSeleccionado = (String) modeloTablaOperadores.getValueAt(filaSeleccionada, 0);
        
        // Paso 4: Crear y mostrar la ventana de modificación
        ModificarOperador ventanaModificar = new ModificarOperador(codigoSeleccionado, this);
        ventanaModificar.setVisible(true);
    }
    
    /**
     * MÉTODO: inicializarEventos()
     * -----------------------------------------------------------------------
     * Configura todos los eventos (listeners) de la ventana.
     * 
     * ¿Qué es un evento?
     * Es una acción que el usuario realiza (hacer clic, escribir, etc.)
     * 
     * ¿Qué es un listener?
     * Es un "escuchador" que espera a que ocurra un evento y ejecuta código.
     * 
     * Aquí configuramos:
     * 1. El filtrado en tiempo real de la tabla (cuando el usuario escribe)
     */
    private void inicializarEventos() {
        // Configurar el tooltip (texto de ayuda) del campo de búsqueda
        txtBusquedaOperador.setToolTipText("Escribe para filtrar operadores (código, nombre o carrera)");
        
        // Paso 1: Crear un TableRowSorter
        // Esto permite filtrar/ordenar las filas de la tabla
        sorterOperadores = new TableRowSorter<>(modeloTablaOperadores);
        TablaOperadores.setRowSorter(sorterOperadores);
        
        // Paso 2: Agregar un DocumentListener al campo de búsqueda
        // Este listener se ejecuta cada vez que el usuario escribe o borra texto
        txtBusquedaOperador.getDocument().addDocumentListener(new DocumentListener() {
            
            // Se ejecuta cuando se inserta texto (el usuario escribe)
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarOperadores(); // Filtrar la tabla
            }
            
            // Se ejecuta cuando se elimina texto (el usuario borra)
            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarOperadores(); // Filtrar la tabla
            }
            
            // Se ejecuta cuando cambian los atributos del texto (raro en campos simples)
            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarOperadores(); // Filtrar la tabla
            }
        });
    }
    
    /**
     * MÉTODO: filtrarOperadores()
     * -----------------------------------------------------------------------
     * Filtra la tabla de operadores según el texto que el usuario escribe.
     * 
     * ¿Cómo funciona?
     * - Si el campo está vacío, muestra todos los operadores
     * - Si hay texto, muestra solo las filas que contienen ese texto
     * 
     * El filtro busca en TODAS las columnas (código, nombre y carrera).
     * 
     * (?i) = case insensitive (no distingue mayúsculas de minúsculas)
     * Ejemplo: si escribes "ing", mostrará "Ingeniería" o "INGENIERÍA"
     */
    private void filtrarOperadores() {
        // Obtener el texto del campo de búsqueda (sin espacios al inicio/final)
        String texto = txtBusquedaOperador.getText().trim();
        
        if (texto.length() == 0) {
            // Si no hay texto, quitar el filtro (mostrar todo)
            sorterOperadores.setRowFilter(null);
        } else {
            // Si hay texto, aplicar filtro con expresión regular
            // (?i) = ignorar mayúsculas/minúsculas
            sorterOperadores.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
        }
    }
    
    /**
     * MÉTODO PÚBLICO: guardarYRecargarOperadores()
     * -----------------------------------------------------------------------
     * Este método es llamado desde las ventanas hijas (AgregarOperador, ModificarOperador)
     * cuando se agrega o modifica un operador.
     * 
     * ¿Qué hace?
     * 1. Guarda todos los usuarios en el archivo cuentas.txt
     * 2. Recarga la tabla para mostrar los cambios
     * 
     * Esto es un ejemplo de "comunicación entre ventanas" (patrón callback).
     */
    public void guardarYRecargarOperadores() {
        // Paso 1: Guardar todos los cambios en el archivo
        guardarUsuariosEnArchivo();
        
        // Paso 2: Recargar la tabla para reflejar los cambios
        cargarOperadoresDesdeArchivo();
    }
    
    // ========================================================================
    // ZONA DE EVENTOS DE BOTONES (Generada por NetBeans)
    // ========================================================================
    // IMPORTANTE: Los comentarios //GEN-FIRST y //GEN-LAST NO deben eliminarse
    // porque NetBeans los usa para identificar el código generado automáticamente.
    
    /**
     * Evento: Click en botón "Regresar al panel principal"
     * Cierra esta ventana y abre el panel principal del administrador.
     */
    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // Cerrar ventana actual y liberar recursos de memoria
        this.dispose();
        
        // Crear y mostrar la ventana del panel de administrador
        PanelAdmin pa = new PanelAdmin();
        pa.setVisible(true);
    }//GEN-LAST:event_btnInicioActionPerformed

    /**
     * Evento: Click en botón "Cerrar sesión"
     * Cierra la sesión del usuario y regresa a la ventana de login.
     */
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // Limpiar el usuario actual (cerrar sesión)
        Inicio.usuarioActual = null;
        
        // Cerrar ventana actual y liberar recursos
        this.dispose();
        
        // Crear y mostrar ventana de login
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * Evento: Click en botón "Generar reportes"
     * Genera archivos HTML con reportes de usuarios y operadores.
     */
    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // Generar reporte HTML de usuarios
        GenerarReportes.generarReporteUsuarios();
        
        // Generar reporte HTML de operadores
        GenerarReportes.generarReporteOperadores();
    }//GEN-LAST:event_btnReportesActionPerformed

    /**
     * Evento: Click en botón "Editar" (operador)
     * Llama al método que abre la ventana de modificación.
     */
    private void btnEditarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarOperadorActionPerformed
        editarOperador();
    }//GEN-LAST:event_btnEditarOperadorActionPerformed

    /**
     * Evento: Click en botón "Agregar" (operador)
     * Llama al método que abre la ventana para agregar un nuevo operador.
     */
    private void btnAgregarOperadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarOperadorActionPerformed
        agregarOperador();
    }//GEN-LAST:event_btnAgregarOperadorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelOperadores;
    private javax.swing.JPanel PanelOperadores1;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelUsuarios;
    private javax.swing.JSeparator SeparadorOperadores;
    private javax.swing.JSeparator SeparadorUsuarios;
    private javax.swing.JTabbedPane TabPanelPrincipal;
    private javax.swing.JTable TablaOperadores;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JButton btnAgregarOperador;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEditarOperador;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReportes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtBusquedaOperador;
    private javax.swing.JTextField txtBusquedaUsuario;
    // End of variables declaration//GEN-END:variables
}
